[package]
name = "zk-checkpoint-program"
version = "0.1.0"
edition = "2021"

[dependencies]
sp1-zkvm.workspace = true
alloy-primitives.workspace = true

serde_json.workspace = true
serde.workspace = true