[package]
version = "0.1.0"
name = "zk-checkpoint-program"
edition = "2021"

[dependencies]
checkpoint-proof = { path = "../consensus-proof" }

sp1-zkvm.workspace = true
reth-primitives.workspace = true
alloy-primitives.workspace = true
alloy-sol-types.workspace = true